color: violet
fieldLayouts:
  c99f682c-cda2-45c5-8356-04806c6866e0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-21T18:58:48+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7e4e5925-8b03-44b7-b3b5-42d13275836b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-22T13:59:17+00:00'
            elementCondition: null
            fieldUid: 5f6b6eba-f03c-49ac-8e1d-9e315d0e19e0 # Description
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d65bb387-dbfb-4d65-af28-5dea4bf5c263
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-21T19:00:23+00:00'
            elementCondition: null
            fieldUid: 8b93b0b3-87e7-4719-9e18-ddf0b482eaf5 # Landing Page Builder
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ceceb14-d172-40d2-96b9-c53fcf6c1677
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-22T13:35:15+00:00'
            elementCondition: null
            fieldUid: b91008b2-e3e9-4b83-a095-430704ed0296 # People Listing
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a144839-17e4-4221-91d4-af36a8f4031d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f197b502-dd72-43fb-b2e1-28cf0b764e1a
        userCondition: null
handle: about
hasTitleField: true
icon: address-card
name: About
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
