color: cyan
fieldLayouts:
  e9129a1d-3c54-4efc-9f78-8efef5f4e56d:
    cardView:
      - 'layoutElement:b9bd0c77-5328-45cf-8a2a-2c05ceb6722d'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-17T04:34:41+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5228ab70-095e-4fe1-8f7d-9cfac72baeb6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-17T04:56:17+00:00'
            elementCondition: null
            fieldUid: 791a0176-d2ea-4094-8330-33b1f63588cd # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85d3c36a-3a5b-4db9-bd51-7fc9dcff77bd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-17T04:56:17+00:00'
            elementCondition: null
            fieldUid: 5f6b6eba-f03c-49ac-8e1d-9e315d0e19e0 # Description
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9bd0c77-5328-45cf-8a2a-2c05ceb6722d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 521f8290-e667-4fda-bc53-79c8c3ccf15d
        userCondition: null
handle: category
hasTitleField: true
icon: layer-group
name: Category
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
