color: pink
fieldLayouts:
  53cc8202-6b9f-42d7-aeaf-77b11a473abe:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-17T03:53:56+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cc266d66-b72b-4d31-81fd-e535c1dbc082
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-17T03:55:32+00:00'
            elementCondition: null
            fieldUid: 5f6b6eba-f03c-49ac-8e1d-9e315d0e19e0 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 06b13cbd-04cf-4a13-8cc4-b7a1c3f08f30
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f8038f36-6b4e-4f05-bedd-054cf3ab7059
        userCondition: null
handle: heading
hasTitleField: true
icon: a
name: Heading
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
