color: amber
fieldLayouts:
  c3304cba-9234-4589-ac35-9cf07b9bdd60:
    cardView:
      - 'layoutElement:ba70db61-3854-4591-b351-f07bae9c5697'
      - 'layoutElement:6299b877-ca41-44ca-879c-441e13588ce6'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-17T04:48:30+00:00'
            elementCondition: null
            fieldUid: 889fde06-2382-4da2-8f42-6622555a0f49 # Categories
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6299b877-ca41-44ca-879c-441e13588ce6
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-03-18T04:07:02+00:00'
            elementCondition: null
            fieldUid: 9fa28bcd-aca4-4b54-888d-84eddc43804f # Related Recipes
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bce24e50-c005-4aa0-9e26-95816deabe5f
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-03-17T22:16:40+00:00'
            elementCondition: null
            fieldUid: 37829aaa-d568-406c-929f-70d8fef00120 # Source
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81dbad06-4a80-4a7c-93a8-5987b6414698
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-03-17T22:16:40+00:00'
            elementCondition: null
            fieldUid: ac800ffd-0a62-4673-9b3b-07b0ddf5ea0e # Rating
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f011ad46-c828-416e-9f6a-19ee123bf919
            userCondition: null
            warning: null
            width: 50
        name: Setup
        uid: 4c462fb6-734a-4742-ae6b-2170b639ca50
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-17T03:37:30+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5261b332-e56d-4220-b96b-7124af6a9b47
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-17T03:43:44+00:00'
            elementCondition: null
            fieldUid: 5f6b6eba-f03c-49ac-8e1d-9e315d0e19e0 # Description
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba70db61-3854-4591-b351-f07bae9c5697
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-17T03:43:44+00:00'
            elementCondition: null
            fieldUid: 791a0176-d2ea-4094-8330-33b1f63588cd # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6760456-53af-4173-8026-3846285f3628
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-03-17T03:43:44+00:00'
            elementCondition: null
            fieldUid: cb74c351-0aab-4e50-a18c-0a5cfc5ca873 # Ingredients and Instructions
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 110f9637-5652-4689-93f1-06678890088b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-18T04:07:02+00:00'
            elementCondition: null
            heading: 'Meta Info'
            type: craft\fieldlayoutelements\Heading
            uid: db0190db-a708-4fed-85a9-d68f3314311e
            userCondition: null
          -
            dateAdded: '2025-03-17T05:22:55+00:00'
            elementCondition: null
            fieldUid: d39d8b85-4ed0-4e5f-a80c-bfbaf45ebb9e # Prep Time
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: edbe2e51-b9a4-4e24-86ba-2124e6ae0b7a
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-03-17T05:22:55+00:00'
            elementCondition: null
            fieldUid: d4add76d-5e84-4ad3-a1ce-63e485462600 # Cook Time
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d1965104-3ab6-4fba-bf92-ba7e12b2501f
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-03-17T05:22:55+00:00'
            elementCondition: null
            fieldUid: 0ef9f8ae-d2ec-443c-a3db-c411267a52fb # Servings
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e4c434d-518a-43c4-add4-384e5c2d243c
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-03-17T05:22:55+00:00'
            elementCondition: null
            fieldUid: 3ef245fe-5223-4cb5-be74-100896771253 # Difficulty
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9140ee6c-af8c-450e-ba6e-ea1f080544ea
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 46ac3eac-952c-4019-8311-98803a9e69af
        userCondition: null
handle: recipe
hasTitleField: true
icon: pot-food
name: Recipe
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
