color: orange
fieldLayouts:
  c8af6b22-2a11-4e6f-9ef2-847330665236:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-17T22:13:07+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7b390e48-f851-4525-862e-c8a8f14e14bf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-17T22:15:25+00:00'
            elementCondition: null
            fieldUid: 2fc1dcc8-9b83-4212-b8d5-5bb5f3725f08 # Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62f00947-b6c2-40ad-8102-9ddda63d159d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c156d0a4-76c3-4a0b-935c-a7564d6afec8
        userCondition: null
handle: source
hasTitleField: true
icon: seedling
name: Source
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
