headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: 'Landing Page'
toolbar:
  - heading
  - bold
  - italic
  - bulletedList
  - numberedList
  - '|'
  - insertImage
  - blockQuote
  - link
  - horizontalLine
  - '|'
  - createEntry
  - '|'
  - sourceEditing
