altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  f7055ec5-6be8-435f-9bf1-d719c697128e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-17T03:54:46+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: b9dcd26b-937b-412a-af45-d2f27e0a7bc2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 08cd13ff-1f40-4ed7-a5d2-e08b8214ccf3
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: imageTransforms
transformSubpath: ''
