columnSuffix: null
handle: instructions
instructions: 'Add the instructions in the correct order'
name: Instructions
searchable: false
settings:
  addRowLabel: 'Add an instruction'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Instruction
            -
              - handle
              - instruction
            -
              - width
              - ''
            -
              - type
              - multiline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
