columnSuffix: null
handle: relatedRecipes
instructions: 'Choose related recipes to display near this one'
name: 'Related Recipes'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Choose a recipe'
  showCardsInGrid: true
  showSiteMenu: false
  sources:
    - 'section:a52b95ef-bea4-4ba7-a1ed-6c1abeaff739' # Recipes
  targetSiteId: null
  validateRelatedElements: false
  viewMode: cards
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
