dateModified: 1742651957
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: '*'
      tableAttributes:
        - status
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: 'Landing Pages'
      type: heading
    -
      key: 'single:45c2b589-716b-45bb-a1c4-a272c488bb72' # Home
      type: native
    -
      defaultSort:
        - id
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'single:e221ba22-80d8-4783-952c-9d1352aef3ee' # About
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      key: 'single:50d3082b-97f0-45e0-b929-b340b014cc14' # Category Listing
      type: native
    -
      heading: Recipes
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:a52b95ef-bea4-4ba7-a1ed-6c1abeaff739' # Recipes
      tableAttributes:
        - 'field:37829aaa-d568-406c-929f-70d8fef00120' # Source
        - 'field:791a0176-d2ea-4094-8330-33b1f63588cd' # Image
        - 'field:889fde06-2382-4da2-8f42-6622555a0f49' # Categories
        - 'field:d39d8b85-4ed0-4e5f-a80c-bfbaf45ebb9e' # Prep Time
        - 'field:d4add76d-5e84-4ad3-a1ce-63e485462600' # Cook Time
        - 'field:0ef9f8ae-d2ec-443c-a3db-c411267a52fb' # Servings
        - 'field:3ef245fe-5223-4cb5-be74-100896771253' # Difficulty
        - 'field:ac800ffd-0a62-4673-9b3b-07b0ddf5ea0e' # Rating
        - status
        - link
      type: native
    -
      heading: Relations
      type: heading
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:f974a3de-1eb2-4b1b-9a38-731ff297975c' # Categories
      tableAttributes:
        - 'field:791a0176-d2ea-4094-8330-33b1f63588cd' # Image
        - slug
        - status
        - link
      type: native
    -
      key: 'section:ea405781-a163-45a6-b02d-389df79ed6bd' # Sources
      type: native
    -
      heading: ''
      type: heading
email:
  fromEmail: heyitsjenni@gmail.com
  fromName: 'Food Not Frenzy'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  imageTransforms:
    hasUrls: true
    name: 'Image Transforms'
    settings:
      path: '@webroot/images/transforms'
    type: craft\fs\Local
    url: $PRIMARY_SITE_URL/images/transforms
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@webroot/images'
    type: craft\fs\Local
    url: $PRIMARY_SITE_URL/images
meta:
  __names__:
    0ef9f8ae-d2ec-443c-a3db-c411267a52fb: Servings # Servings
    00fcd939-7a66-4a0d-846e-c94744f9afbd: 'Instructions Block' # Instructions Block
    2c854352-be15-4589-a7bc-8f9afb8fe084: 'Landing Page' # Landing Page
    2fc1dcc8-9b83-4212-b8d5-5bb5f3725f08: Link # Link
    3ef245fe-5223-4cb5-be74-100896771253: Difficulty # Difficulty
    4a693010-b1d3-4360-83f6-286e15b1e003: Images # Images
    5acbae4c-d457-4bae-bd1e-64eafe66aba1: Heading # Heading
    5f6b6eba-f03c-49ac-8e1d-9e315d0e19e0: Description # Description
    6ee21a4c-5f40-41dc-9ce7-7ecf02b65a61: 'Food Not Frenzy' # Food Not Frenzy
    8b93b0b3-87e7-4719-9e18-ddf0b482eaf5: 'Landing Page Builder' # Landing Page Builder
    9cd023d0-050c-43d7-872c-0f04e40a4ce2: 'First Name' # First Name
    9f1a37e6-5a3b-422c-9023-05dc6881f215: Category # Category
    9fa28bcd-aca4-4b54-888d-84eddc43804f: 'Related Recipes' # Related Recipes
    45c2b589-716b-45bb-a1c4-a272c488bb72: Home # Home
    50d3082b-97f0-45e0-b929-b340b014cc14: 'Category Listing' # Category Listing
    52d39acd-303a-4735-888f-96d078e5421e: Recipe # Recipe
    53db4810-9435-425e-8a67-19c3a758ac44: 'Last Name' # Last Name
    76c307ef-e80f-4554-aea2-97e5bc786f15: 'Total Time' # Total Time
    435de420-224b-4488-91de-bf647d9fbd87: 'Professional Title' # Professional Title
    740f5d4b-c988-444f-851c-d89f48e185f7: Instructions # Instructions
    791a0176-d2ea-4094-8330-33b1f63588cd: Image # Image
    889fde06-2382-4da2-8f42-6622555a0f49: Categories # Categories
    891b58b4-599f-490c-8dcd-7d080f86a696: Source # Source
    37829aaa-d568-406c-929f-70d8fef00120: Source # Source
    7954968a-6a99-4703-acb6-fdbafee96a77: People # People
    39207932-cedb-4c50-adcd-6b0d32a116aa: Headshot # Headshot
    98033637-a135-47f7-99e1-67a4a00f53af: Simple # Simple
    a4d34421-d53c-4cc7-beb0-734bfd880ba6: 'Ingredients Block' # Ingredients Block
    a52b95ef-bea4-4ba7-a1ed-6c1abeaff739: Recipes # Recipes
    ac800ffd-0a62-4673-9b3b-07b0ddf5ea0e: Rating # Rating
    b2ead43b-fee4-4670-92fb-5937a95908d9: 'Food Not Frenzy' # Food Not Frenzy
    b91008b2-e3e9-4b83-a095-430704ed0296: 'People Listing' # People Listing
    be7087e0-632e-4e28-bb57-7c20bb7349b7: Person # Person
    bf627ebc-3e6c-4e74-9399-6199acd72d96: About # About
    cb74c351-0aab-4e50-a18c-0a5cfc5ca873: 'Ingredients and Instructions' # Ingredients and Instructions
    cdf03fe9-480e-4e08-8a4d-1c98ac6433e9: 'Landing Page' # Landing Page
    d4add76d-5e84-4ad3-a1ce-63e485462600: 'Cook Time' # Cook Time
    d8ea3146-9c3b-484e-bdbf-bd7fab1e6d42: 'Ingredients List' # Ingredients List
    d39d8b85-4ed0-4e5f-a80c-bfbaf45ebb9e: 'Prep Time' # Prep Time
    e221ba22-80d8-4783-952c-9d1352aef3ee: About # About
    ea405781-a163-45a6-b02d-389df79ed6bd: Sources # Sources
    f974a3de-1eb2-4b1b-9a38-731ff297975c: Categories # Categories
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  component-library:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  copy:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  environment-label:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  expanded-singles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  fortrabbit-object-storage:
    edition: standard
    enabled: true
    schemaVersion: '2.0'
  seomate:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Food Not Frenzy'
  schemaVersion: 5.6.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
