defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: be7087e0-632e-4e28-bb57-7c20bb7349b7 # Person
handle: people
maxAuthors: 1
name: People
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  b2ead43b-fee4-4670-92fb-5937a95908d9: # Food Not Frenzy
    enabledByDefault: true
    hasUrls: true
    template: people/_entry.twig
    uriFormat: 'people/{slug}'
type: channel
