defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 52d39acd-303a-4735-888f-96d078e5421e # Recipe
handle: recipes
maxAuthors: 1
name: Recipes
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  b2ead43b-fee4-4670-92fb-5937a95908d9: # Food Not Frenzy
    enabledByDefault: true
    hasUrls: true
    template: _channels/recipe.twig
    uriFormat: 'recipes/{slug}'
type: channel
